### ISSUE TITLE
Release `kuma_utils` as a PyPI package

### ISSUE THREAD

**Issue by sugatoray** [analokmaus/kuma_utils#10]
Please consider releasing `kuma_utils` as a PyPI package.

**Comment by sugatoray** [comment]
I got to know about this repository and `LGBMImputer` at a video presentation on imputation of missing values by **`Rob Mulla`** at **`Abhishek Thakur's`** YouTube channel.

- YouTube Video: https://youtu.be/GW45jLkU1kU?t=3691 🚀 🔥 

<a href="https://youtu.be/GW45jLkU1kU?t=3691">
    <img width="1512" alt="LGBMImputer_demo" src="https://user-images.githubusercontent.com/10201242/193812055-68079265-33e3-4643-ae54-2c838f14ed7d.png">
</a>

cc: @RobMulla @abhishekkrthakur

**Comment by analokmaus** [comment]
Sorry for the inconvenience, but now you can install kuma_utils locally using poetry. Please follow the instructions in the README.
