### ISSUE TITLE
Missing columns on test set

### ISSUE THREAD

**Issue by nam-d-doan** [analokmaus/kuma_utils#9]
In my project, I have implemented the LGBMImputer in your package for data imputation. And as usual, I first fit and transform the train set, then transform the test set.

**ISSUE**: The columns with missing data in my train set and in test set are different and it appears that the "fit" function only train model and regress on the **feature_with_missing** of train data, and left several other columns in test set with data still missing if those columns is not in the feature_with missing from train set.

The solution I have applied in my project is to 'fit' regression on all train columns, and 'transform' feature missing (see attachment for my changed codes).
I'm not yet adept in coding, still, I'd imagine it may increase the execution time so I will leave this issue here for any better solution.

[imputer.txt](https://github.com/analokmaus/kuma_utils/files/9153890/imputer.txt)

**Comment by analokmaus** [comment]
I have added a new argument `target_cols` in the latest version (v0.4.0).
Adding those columns to  `target_cols` should be fine.

https://github.com/analokmaus/kuma_utils/blob/f33232f7220d7a2feac7c0eacf3ba250cf74818e/kuma_utils/preprocessing/imputer.py#L40
